name: Bump

on:
  issue_comment:
    types: [created]

jobs:
  chart-version:
    name: Chart Version
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Check for command
        id: command
        continue-on-error: true
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const commentBody = context.payload.comment.body;
            const commandPrefix = "/bump ";
            let commandName = "";
            let chartName = "";
            let bumpLevel = "";

            if (commentBody.startsWith(commandPrefix)) {
              commandName = "bump";
              const args = commentBody.slice(commandPrefix.length).trim().split(" ");
              
              if (args.length > 0 && args[0]) {
                chartName = args[0];
                bumpLevel = args[1] || "patch"; 

                console.log(`Chart Name: ${chartName}, Bump Level: ${bumpLevel}`);
                console.log(`Args array: ${JSON.stringify(args)}`);

                const fs = require('fs');
                fs.appendFileSync(process.env.GITHUB_OUTPUT, `chart-name=${chartName}\n`);
                fs.appendFileSync(process.env.GITHUB_OUTPUT, `bump-level=${bumpLevel}\n`);
                fs.appendFileSync(process.env.GITHUB_OUTPUT, `command-name=${commandName}\n`);

              } else {
                commandName = "";
                core.warning("No chart name provided. Format: /bump <chart-name> [level]");
                }
            }

      - name: Add eyes reaction
        if: steps.command.outputs.command-name == 'bump'
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        if: steps.command.outputs.command-name == 'bump'
        with:
          python-version: 3.13

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        if: steps.command.outputs.command-name == 'bump'
        with:
          go-version: ^1

      - name: Setup helm-docs
        if: steps.command.outputs.command-name == 'bump'
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest

      - name: Checkout Repository
        if: steps.command.outputs.command-name == 'bump'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Pull Request
        if: steps.command.outputs.command-name == 'bump'
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        if: steps.command.outputs.command-name == 'bump'
        id: get_version
        uses: mikefarah/yq@f03c9dc599c37bfcaf533427211d05e51e6fee64 # v4.47.1
        with:
          cmd: yq ".version" charts/${{ steps.command.outputs.chart-name }}/Chart.yaml

      - uses: actions-ecosystem/action-bump-semver@34e334551143a5301f38c830e44a22273c6ff5c5 # v1
        if: steps.command.outputs.command-name == 'bump'
        id: semver
        with:
          current_version: ${{ steps.get_version.outputs.result }}
          level: ${{ steps.command.outputs.bump-level }}

      - name: Bump the version
        if: steps.command.outputs.command-name == 'bump'
        uses: mikefarah/yq@f03c9dc599c37bfcaf533427211d05e51e6fee64 # v4.47.1
        with:
          cmd: yq -i '.version = "${{ steps.semver.outputs.new_version }}"' charts/${{ steps.command.outputs.chart-name }}/Chart.yaml

      - name: Run pre-commit
        if: steps.command.outputs.command-name == 'bump'
        id: pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        continue-on-error: true

      - name: Check pre-commit results
        if: steps.command.outputs.command-name == 'bump'
        run: |
          if [ "${{ steps.pre-commit.outcome }}" = "failure" ]; then
            echo "Pre-commit hooks made changes to files (this is expected)"
            echo "Changes will be committed in the next step"
          else
            echo "Pre-commit hooks completed without making changes"
          fi

      - name: Check files changed
        if: steps.command.outputs.command-name == 'bump'
        run: |
          echo "=== Git status ==="
          git status
          echo "=== Files changed ==="
          git diff --name-only
          echo "=== Chart directory contents ==="
          ls -la charts/${{ steps.command.outputs.chart-name }}/

      - name: Commit pre-commit changes
        if: steps.command.outputs.command-name == 'bump'
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: Bump ${{ steps.command.outputs.chart-name }} version to ${{ steps.semver.outputs.new_version }}
          file_pattern: "charts/${{ steps.command.outputs.chart-name }}/"
          add_options: '-A'
