name: SNYK

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  # schedule:
  #   - cron: "0 0 * * 0"  # Re-enable after validation

jobs:
  scan-iac:
    name: Scan Rendered Templates
    runs-on: ubuntu-latest

    strategy:
      matrix:
        chart:
          - name: backstage
            path: ./charts/backstage
            output: ./output/backstage
          - name: orchestrator-infra
            path: ./charts/orchestrator-infra
            output: ./output/orchestrator-infra

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: v3.17.0

      - name: Render Templates
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add backstage https://backstage.github.io/charts
          helm repo update
          helm dependency build ${{ matrix.chart.path }}
          helm template ${{ matrix.chart.path }} --output-dir ${{ matrix.chart.output }}

      - name: Run Snyk IaC Scan
        continue-on-error: true
        uses: snyk/actions/iac@b98d498629f1c368650224d6d212bf7dfa89e4bf # 0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
        with:
          args: --report --org=$SNYK_ORG_ID --target-name="redhat-developer/rhdh-chart/${{ matrix.chart.name }}"
          file: ${{ matrix.chart.output }}
