name: Test Workflow

on:
  push:
    branches: [ example-bumping-chart-versions ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Workflow is working!"
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}" 